Repository wecode-bootcamp-korea/15-2nd-anotherclass101-backend, pull requests merged in 2021-01, with the labels that each got.

#3 [어나더클라스101 석여주]Modify : 메인카테고리&좋아요 리뷰반영 및 UnitTest 완성
  .DS_Store
  ac101/urls.py
  community/migrations/0001_initial.py
  community/migrations/0002_auto_20210106_0334.py
  curriculum/migrations/0001_initial.py
  curriculum/migrations/0002_auto_20210106_0334.py
  product/.DS_Store
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20210106_0334.py
  product/migrations/0003_auto_20210106_2259.py
  product/models.py
  product/tests.py
  product/urls.py
  product/views.py
  request/migrations/0001_initial.py
  request/models.py
  user/migrations/0001_initial.py
  user/models.py
  user/utils.py
Labels: Status: Accepted

#4 [어나더클라스101 이재혁] Add: course 개설 request 생성 및 내용 입력 API 구현
  .gitignore
  ac101/settings.py
  ac101/storages.py
  ac101/urls.py
  community/migrations/0001_initial.py
  community/migrations/0002_auto_20210107_2121.py
  curriculum/migrations/0001_initial.py
  curriculum/migrations/0002_auto_20210107_2121.py
  curriculum/models.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20210107_2121.py
  product/migrations/0003_auto_20210106_2259.py
  product/models.py
  request/migrations/0001_initial.py
  request/models.py
  request/tests.py
  request/urls.py
  request/views.py
  user/migrations/0001_initial.py
  user/models.py
  user/utils.py
Labels: Status: 수정 요청

#5 [어나더클라스101 김민철] Add: 회원가입/로그인/문자인증 구현
  .DS_Store
  ac101/settings.py
  ac101/urls.py
  community/migrations/0001_initial.py
  community/migrations/0002_auto_20210107_2121.py
  curriculum/migrations/0001_initial.py
  curriculum/migrations/0002_auto_20210107_2121.py
  product/.DS_Store
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20210107_2121.py
  product/models.py
  request/migrations/0001_initial.py
  request/models.py
  user/migrations/0001_initial.py
  user/models.py
  user/tests.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: 리뷰 요청

#7 Create README.md
  README.md
Labels: Status: 도움 요청, Status: 리뷰 요청
